import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import fs from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// In dev mode, build straight into the test vault so pjeby/hot-reload picks
// up changes. Production builds emit main.js at the repo root (release asset).
const devPluginDir = path.join("test-vault", ".obsidian", "plugins", "slashosaurus");
const outfile = prod ? "main.js" : path.join(devPluginDir, "main.js");

if (!prod) {
	fs.mkdirSync(devPluginDir, { recursive: true });
	fs.copyFileSync("manifest.json", path.join(devPluginDir, "manifest.json"));
	fs.copyFileSync("styles.css", path.join(devPluginDir, "styles.css"));
	fs.writeFileSync(path.join(devPluginDir, ".hotreload"), "");
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
		...builtinModules.map((m) => `node:${m}`),
	],
	format: "cjs",
	target: "es2021",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile,
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
